import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";

// Khai báo metadata tĩnh cho trang web (hiển thị trên tab trình duyệt và SEO).
export const metadata: Metadata = {
  title: "Chat App",  // Tiêu đề của trang web xuất hiện trên tab trình duyệt.
  description: "Generated by create next app", // Mô tả ngắn gọn về ứng dụng
};

// Khai báo RootLayout là component gốc (layout chung) bọc toàn bộ các trang trong ứng dụng Next.js.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning> {/* Thẻ HTML gốc của trang, đặt ngôn ngữ tiếng Anh và tắt cảnh báo lệch mã HTML SSR/Client (hydration warning). */}
      <body>
        {/* AppProvider là một Context Provider, đóng vai trò quản lý trạng thái toàn cục của ứng dụng (như thông tin người dùng, danh sách chat, trạng thái kết nối WebSocket). */}
        <AppProvider>
          {children} {/* Render các trang con (ví dụ: trang login, trang ChatApp,...) tương ứng với đường dẫn URL hiện tại. */}
        </AppProvider>
      </body>
    </html>
  );
}
