import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { SocketProvider } from "@/context/SocketContext";

// Khai báo metadata tĩnh cho trang web (hiển thị trên tab trình duyệt và SEO).
export const metadata: Metadata = {
  title: "Chat App",  // Tiêu đề của trang web xuất hiện trên tab trình duyệt.
  description: "Generated by create next app", // Mô tả ngắn gọn về ứng dụng
};

// Khai báo RootLayout là component gốc (layout chung) bọc toàn bộ các trang trong ứng dụng Next.js.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppProvider>
          <SocketProvider>
            {children}
          </SocketProvider>
        </AppProvider>
      </body>
    </html>
  );
}
